### ISSUE TITLE
compilation errors in the library

### ISSUE THREAD

**Issue by skippyall** [senseiwells/EssentialClient#100]
When running a client script using the minecraft library, I get a compilation error
![grafik](https://user-images.githubusercontent.com/121978267/219766197-ce86f43e-4339-4d75-b55b-353e2b861405.png)

**Comment by skippyall** [comment]
It seems to have to do something with the ... argument, when commenting this line out, the next one with this argument type throws an error

**Comment by senseiwells** [comment]
You are importing the stubs.
This means you are likely doing this:
```kotlin
import * from minecraft;
```
But you need to do this:
```kotlin
import * from Minecraft;
```

**Comment by skippyall** [comment]
Oh, in the wiki it says you should import minecraft in small case

**Comment by senseiwells** [comment]
Where in the wiki does it say that?
