### ISSUE TITLE
lecternTrade throws error when attempting to add enchant

### ISSUE THREAD

**Issue by mr-hespicable** [senseiwells/EssentialClient#101]
the script lecternTrade throws this error when trying to add an enchant
![image](https://user-images.githubusercontent.com/85052021/219789251-aa8aeadc-35f9-40be-8ca4-4fa4d954dcf6.png)

to reproduce:
run lecternTrade
run the command `/lecternTrade addEnchant minecraft:thorns 3 20`
the error should appear

i might just be doing the command wrong tho so im sorry if this issue is stupid ;-;

**Comment by senseiwells** [comment]
Fixed in 4f7d5a077ab96a2a7a087a35443c74c1f349c17a.

You can download it in the dev build:
https://github.com/senseiwells/EssentialClient/actions/runs/4207802835
