### ISSUE TITLE
Client.addCommand()

### ISSUE THREAD

**Issue by JiangZeOvO** [senseiwells/EssentialClient#102]
parameter "arguments" Type inside
Is there a "String" type Instead of "GreedyString"
If you create an instruction with two "GreedyStrings", it will not work
eg:
![image](https://user-images.githubusercontent.com/101352564/220714202-1666b7e2-ce21-412c-8f4f-b8d71661a1ee.png)
![image](https://user-images.githubusercontent.com/101352564/220715129-41228ebd-8af5-44e1-a635-19c01f8b9518.png)
"Item" will also match the parameters of "int" in it, resulting in that "int" has no parameters to use

**Comment by JiangZeOvO** [comment]
The first parameter is that all parameters after the GreedyString type cannot match

**Comment by aria1th** [comment]
Its vanilla behavior, since GreedyString is 'greedy' string that tries to get everything as string.

**Comment by JiangZeOvO** [comment]
What should I do if I just want him to match a string without greedy matching

**Comment by senseiwells** [comment]
You'd use "word", it only captures letters and stops after a space

**Comment by JiangZeOvO** [comment]
What I need to deliver is the Chinese of the item
