### ISSUE TITLE
Network.downloadFile() Download failed

### ISSUE THREAD

**Issue by JiangZeOvO** [senseiwells/EssentialClient#104]
![image](https://user-images.githubusercontent.com/101352564/221524564-15b99528-b587-4e51-900a-3843dd95646a.png)

Website splicing is correct Download directly using Google

But the return value of the function is false

Nor did it download successfully

**Comment by senseiwells** [comment]
Sorry for the late reply - the reason that the file doesn't download successfully is because your file is listed as the `/Scripts` directory, this is what you probably mean:
```kotlin
file = new File("config/EssentialClient/Scripts/Shop.php");
Network.downloadFile(config_url + "Shop.php", file);
```
I have tested this and it works.
