### ISSUE TITLE
ViaFabricPlus Incompaticlblbl

### ISSUE THREAD

**Issue by pierrelasse** [senseiwells/EssentialClient#106]
**ViaFabricPlus** (https://github.com/FlorianMichael/ViaFabricPlus/)
Last line before crash:
`@ModifyConstant conflict. Skipping viafabricplus.mixins.json:fixes.MixinStringHelper from mod viafabricplus->@ModifyConstant::expandChatLength(I)I with priority 1000, already redirected by essentialclient.mixins.json:longChatMessages.StringHelperMixin from mod essential-client->@ModifyConstant::getMaxLength(I)I with priority 1000`

I think you will have more fun download it yourself than figuring out what from my logs is needed.

**Comment by pierrelasse** [comment]
Did you fix it?

**Comment by senseiwells** [comment]
Yes, you can download the fixed version in a dev build
