### ISSUE TITLE
Issue: Cannot read field "field_1724" because the return value of "me.senseiwells.essentialclient.utils.EssentialUtils.getClient()" is null

### ISSUE THREAD

**Issue by NopeProsOnly** [senseiwells/EssentialClient#112]
![image](https://user-images.githubusercontent.com/78925970/233684761-43bf184e-dafa-43f2-a972-50f6f067e463.png)

**Comment by NopeProsOnly** [comment]
Seems the problem is with this mod

https://modrinth.com/plugin/cae2

**Comment by senseiwells** [comment]
You can download the fixed version [here](https://github.com/senseiwells/EssentialClient/actions/runs/4774778743/jobs/8488672357)
