### ISSUE TITLE
Conflict with Chat Heads

### ISSUE THREAD

**Issue by Fourmisain** [senseiwells/EssentialClient#119]
Hey, current maintainer of Chat Heads here.

There's a crashing Mixin conflict https://github.com/dzwdz/chat_heads/issues/52 between our mods, specifically with this `@Redirect`:

https://github.com/senseiwells/EssentialClient/blob/f54bbe7fb5d10ba1a213cfc1016ad46115938f25/src/main/java/me/senseiwells/essentialclient/mixins/clientScript/ClientPlayNetworkHandlerMixin.java#L140-L149

Here's [our side](https://github.com/dzwdz/chat_heads/blob/bef6e9ae2ba43a77cbdd0c5309a81788d9cf36ca/common/src/main/java/dzwdz/chat_heads/mixin/ClientPacketListenerMixin.java#L29-L52) (using Mojmaps).

The issues is that the `@Redirect` will replace the targeted `MessageHandler.onChatMessage()` method call with a callback method which then cannot be targeted by our `@Inject`/`@ModifyArg` anymore.

There's actually no need to use a `@Redirect` here. You can simply use an `@Inject` with the same target and capture the locals, using `.get()` on the `Optional<MessageType.Parameters>` and `.getProfile()` on the `PlayerListEntry` just like the vanilla code does.
Alternatively you could also use a `@ModifyArgs` (note the "s") and just read the parameters without changing them.

**Comment by senseiwells** [comment]
Hi, thanks for making me aware of this conflict.

Unfortunately this cannot be replaced by `@Inject` or `ModifyArgs` as the redirect is allowing me to completely cancel the method call which I am doing. Well you could cancel with an `@Inject` but that causes much worse issues as it is harder to detect (for mods that inject at the tail of a method or after I cancel.

However MixinExtras provides `@WrapWithCondition` so I've used that instead which should resolve this issue 👍.

**Comment by Fourmisain** [comment]
Ah right, I didn't even notice the `if`. Good ol' MixinExtras coming in to save the day!
Thanks for the quick respone!
