### ISSUE TITLE
File.open() doesn't work

### ISSUE THREAD

**Issue by unin-able** [senseiwells/EssentialClient#128]
title

images and logs below

log:
https://mclo.gs/wLHuEKO

images:
(file exists)
![explorer_YjLoHUjB04](https://github.com/senseiwells/EssentialClient/assets/107908737/c5ec9aa7-95f5-4df6-9c4d-a471d4746495)
![sublime_text_nVuaooUxVf](https://github.com/senseiwells/EssentialClient/assets/107908737/3aed635b-61e2-4137-a2a5-00d5d09ba254)
![javaw_kroDsK3zfw](https://github.com/senseiwells/EssentialClient/assets/107908737/f7ca7fc6-9b84-4211-9102-1302fc4c45d2)

(script file)
![image](https://github.com/senseiwells/EssentialClient/assets/107908737/6e3f6ca6-6347-4e4f-ad3f-3ca310e067c9)

**Comment by senseiwells** [comment]
What is the absolute path of this file?

**Comment by unin-able** [comment]
`E:\Programs\PrismLauncher\instances\1.16.5 Fabric\.minecraft`
