### ISSUE TITLE
[Bug]: Crash on launch when using ViaVersionPlus

### ISSUE THREAD

**Issue by pierrelasse** [senseiwells/EssentialClient#130]
Here the log with ViaFabricPlus
[crash.txt](https://github.com/senseiwells/EssentialClient/files/14469712/crash.txt)
and here without
[working.txt](https://github.com/senseiwells/EssentialClient/files/14469714/working.txt)

ViaFabricPlus v3.0.6
Essential Client v1.4.1
Carpet Mod v1.4.128+v231205

Essential Client (not Carpet Mod) is causing the problem.

**Comment by senseiwells** [comment]
Duplicate of #125
