### ISSUE TITLE
Trojan Detected in latest version 1.20.1

### ISSUE THREAD

**Issue by aMazeInRunar** [senseiwells/EssentialClient#131]
![image](https://github.com/senseiwells/EssentialClient/assets/56029443/ff05d34f-7311-4dec-853c-dd367dc9c9c5)

**Comment by aMazeInRunar** [comment]
Not the first mod released this month with this issue, EnchantedShulkers has it too.

**Comment by senseiwells** [comment]
Putting it through VirusTotal seems to be fine. Doing some looking into this I found [this post](https://www.spigotmc.org/threads/windows-defender-false-positives.639507/). It's very likely that it's a false positive - you can also check the `SHA-256` hash of your file, it should be: `dd9b1e1981afdc81b48ed85ac03a897d68a9edb25a4e2778986a37b9b67aad13`.

I do not have access to a windows machine to reproduce this issue unfortunately.
