### ISSUE TITLE
Custom Item Definition and Display in FakeScreen with New Component System in Minecraft 1.20.6

### ISSUE THREAD

**Issue by JiangZeOvO** [senseiwells/EssentialClient#137]
I'm writing to inquire about how to define a custom item and display it in a FakeScreen in Minecraft 1.20.6, considering the recent changes Mojang made by replacing NBT with a component-based system.
Previously, I used ItemStack.parse to edit NBT data to display custom items. However, with the new system, I'm unsure of the appropriate method to achieve this. Is there a new way to define and display custom items, or is it currently not possible?

**Comment by senseiwells** [comment]
Closing as won't fix, I plan on reworking the entire scripting system for the future.
