### ISSUE TITLE
Water flowing on block sides rendering under water on glass. (fabric 1.20.1)

### ISSUE THREAD

**Issue by Ketari-G** [senseiwells/EssentialClient#138]
To recreate the issue:
1. Install fabric, fabric api, carpet and essential client (all latest versions)
2. Go into any world, underwater (in a ocean for example)
3. Place glass or stained glass, any color
4. This will happen:
![2024-06-04_22 38 16](https://github.com/senseiwells/EssentialClient/assets/136245246/31f89f8a-91c3-477f-899f-779da0d52997)

If you then disable essential client specifically, this is how it should look like: (vanilla behaviour)
![2024-06-04_22 40 57](https://github.com/senseiwells/EssentialClient/assets/136245246/907d540b-a424-4131-a483-10c76e780f9b)

I have tested with only those core mods and nothing else, as well as tried searching in essential's config for a fix to this issue, couldn't find anything.

**Comment by senseiwells** [comment]
This has been fixed in the most recent EssentialClient release
