### ISSUE TITLE
Feature Request: Middle Click Recipe & "craftinghax"

### ISSUE THREAD

**Issue by the-just-luke** [senseiwells/EssentialClient#14]
In 1.12 carpet client, you are able to middle-click a recipe and it will put whatever item it is in the search bar permanently until you remove it so that you can't accidentally craft something else. This feature I believe was meant to go along with the option "craftinghax" from useful mod where you hold ctrl and shift then left-click on a recipe and it with craft a stack of the item of choice and throw it out as well. I probably butchered the explanation of how both work but I hope it was sufficient.

**Comment by senseiwells** [comment]
I've added Middle Click Recipe, although craftinghax is a little more difficult as crafting recipies is handled server side. 

@Crec0 might be able to add this with new crafting implementation :)

**Comment by senseiwells** [comment]
This has been added
