### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by ChrqnosMC** [senseiwells/EssentialClient#143]
I'm sending you the crash report to help you find the source of the problem, but I don't think I can help you any further.
https://mclo.gs/nJuDYjS

**Comment by senseiwells** [comment]
Please update EssentialClient to the latest version

**Comment by ChrqnosMC** [comment]
I'm on the latest version

**Comment by ChrqnosMC** [comment]
I'm playing in 1.21 and version 1.5.2 is the latest version available

**Comment by senseiwells** [comment]
All 1.21.1 mods will work on 1.21

I forgot to mark it as being compatible

https://modrinth.com/mod/essentialclient/version/2.0.0-beta.2+1.21.1

**Comment by ChrqnosMC** [comment]
I tried with beta versions 1.21.1 and 1.21.3 of the mods but it doesn't change anything. I still have the same crash as the release version 1.5.2.

**Comment by senseiwells** [comment]
Can you please provide the crash log for the 1.21.1 version.

And can you confirm this crash happens without EssentialClient installed?

**Comment by ChrqnosMC** [comment]
I can state with certainty that the crash does not occur without EssentialClient installed

https://mclo.gs/hQH14Up

**Comment by senseiwells** [comment]
You have the wrong version installed, please install the **1.21.1** version and send the crash log

**Comment by ChrqnosMC** [comment]
I wasn't paying attention but I was installing it via my modpack made on the modrinth application and it was installing the latest version of the project despite the fact that I selected version 1.21.1 but I've bypassed this problem and I no longer have the crash, thank you.
