### ISSUE TITLE
BetterPingDisplay conflits with... Better Ping Display?

### ISSUE THREAD

**Issue by IJustWantANamePlease** [senseiwells/EssentialClient#18]
When both Essencial Client and Better Ping Display are loaded game crashes. This is part of the log that I believe is relavent.

[Render thread/WARN]: @Redirect conflict. Skipping essentialclient.mixins.json:toggleTab.InGameHudMixin->@Redirect::onRender(Lnet/minecraft/class_355;Lnet/minecraft/class_4587;ILnet/minecraft/class_269;Lnet/minecraft/class_266;)V with priority 1000, already redirected by betterpingdisplay.mixins.json:InGameHudMixin->@Redirect::render(Lnet/minecraft/class_355;Lnet/minecraft/class_4587;ILnet/minecraft/class_269;Lnet/minecraft/class_266;)V with priority 1000

I totally understand if you are not in favour of fixing this, as this function seems to entirly included in Essencial Client. But I do suggest putting a notice in mod discription for people like me, who have Better Ping Display before adding this mod.

**Comment by senseiwells** [comment]
Yes I made BetterPingDisplay to replace the mod. Better ping display is very poorly implemented, it completely rewrites a huge chunk of code unnecessarily causing lots of conflicts including one of my other features ToggleTab. So I rewrote the BetterPingDisplay so it doesn’t conflict with stuff. So yea this is Won’t fix
