### ISSUE TITLE
Script crashing game

### ISSUE THREAD

**Issue by erv123** [senseiwells/EssentialClient#29]
The following script runs fine for a while and then the game crashes

client = getMinecraftClient();
world = client.getWorld();
me = client.getPlayer();
me.look(54.1,70.9);
blockCheck = world.getBlockAt(-6913,100,18869);
itemCheck = me.getHeldItem();
me.message(itemCheck);

while(me.getHeldItem() == itemCheck){
    while(world.getBlockAt(-6913,108,18869)==blockCheck){
    me.use("once");
        if(me.getHeldItem()!=itemCheck)
            return;
        if(world.getBlockAt(-6912,112,18869)==blockCheck){
            sleep(100);
        }
        else{
            sleep(500);
        }
    }
sleep(5000);
}

the launcher told me this:
The game crashed whilst unexpected error
Error: java.util.ConcurrentModificationException
Exit Code: -1

full crash report
[crash-2021-12-27_18.33.52-client.txt](https://github.com/senseiwells/EssentialClient/files/7781374/crash-2021-12-27_18.33.52-client.txt)

**Comment by senseiwells** [comment]
Can you provide mod version, and game version?
