### ISSUE TITLE
"Cannot set that value"

### ISSUE THREAD

**Issue by Wudji** [senseiwells/EssentialClient#31]
Game version:1.18.1 
EssentialClient:1.1.2
The following code throws "Cannot set that value": 
`client = getMinecraftClient();

client.setEssentialClientRule("highlightLavaSources", false);//or "false" , true, "true"

hold();`
(Copied from [here](https://github.com/senseiwells/EssentialClient/wiki/ClientScript#minecraftclientsetessentialclientrulerulename-value))

but it works well with other rules(such as commandSuggestorIgnoresSpaces ...)

**Comment by senseiwells** [comment]
forgot to reply to this, xD
thanks will be fixed in next version
