### ISSUE TITLE
server carpetrule & gamerule not working

### ISSUE THREAD

**Issue by Pi3tro88** [senseiwells/EssentialClient#43]
on server, carper rule menu is completly empty, and gamerule menu button is disabled, obviously i am op

**Comment by senseiwells** [comment]
Could you please provide your Game Version, Essential Client Version, screenshots, etc.

Gamerules are also only available in singleplayer.

**Comment by Pi3tro88** [comment]
ah ok i didnt know that
game versione: 1.18.1
essential client version: 1.1.6
btw is pretty sus, before the menu was empty, now its not, but all buttons are disabled, like i am not op
![image](https://user-images.githubusercontent.com/88508843/154983832-b794f165-0816-479f-9f05-a1d40d65975f.png)

**Comment by Pi3tro88** [comment]
yes, of course

**Comment by senseiwells** [comment]
Does this work in single player?

**Comment by Pi3tro88** [comment]
yep

**Comment by senseiwells** [comment]
Ok this should be fixed for next release

**Comment by Pi3tro88** [comment]
Top

**Comment by senseiwells** [comment]
This has been fixed for the next update
