### ISSUE TITLE
Yaw and pitch are switched in /playerclient command

### ISSUE THREAD

**Issue by Krebs-Cycle** [senseiwells/EssentialClient#45]
I'm running version 1.1.6 in 1.17.1
When adding a new player with the /playerclient command you now need to type the pitch and then yaw when specifying the "facing" part of the command compared to previous behavior. The vanilla commands and the carpet player command both use yaw first and then pitch, which essential client also followed before (works correctly in 1.1.2 and maybe later, but I didn't test the other versions in between).

**Comment by senseiwells** [comment]
Yup, should be fixed in next release thanks
