### ISSUE TITLE
Figura incompatibility

### ISSUE THREAD

**Issue by lenrik1589** [senseiwells/EssentialClient#46]
Figura is a client-side mod for creating custom avatars, and in one of it's mixins it does has a `@Redirect` that clashes with essential client's `@Redirect` onto the same method call, I think `@Inject`s are preferable where possible, and looking at [maruohon/tweakeroo](https://github.com/maruohon/tweakeroo/tree/fabric_1.18_temp_features) there is a way to implement that functionality w/o use of a redirect, here's the `@Redirect` in question in [tweakeroo](https://github.com/maruohon/tweakeroo/blob/cc86f071f4ae585cb560a0078e2acf9b0d4776dc/src/main/java/fi/dy/masa/tweakeroo/mixin/MixinInGameHud.java#L50)(well, not a `@Redirect` here, but), [Figura](https://github.com/Blancworks/Figura/blob/0ee35a0d6d5452145ee5959851522b512f6e4149/src/main/java/net/blancworks/figura/mixin/InGameHudMixin.java#L59) and [EssetialClient](https://github.com/senseiwells/EssentialClient/blob/0ffd664ebaa694d760e39134a3ce0ee5e173f789/src/main/java/me/senseiwells/essentialclient/mixins/toggleTab/InGameHudMixin.java#L27). And since both Figura and EssenialClient use a redirect, since one of those is guaranteed to fail, game crashes at startup.

**Comment by senseiwells** [comment]
This should be resolved now
