### ISSUE TITLE
Incompatibility with feather client

### ISSUE THREAD

**Issue by Noah765** [senseiwells/EssentialClient#49]
Hi, I am kind of a technical mc player, but I play pvp as well. I recently saw a pvp client called feather client which is based of fabric (it is more a mod itself, then a normal client). I tried using this client with mods like litematica and tweakeroo and it works fine, but it does not work with your essential client mod. I dont know much about programming and how mods exactly work. I will send the log.

[latest.log](https://github.com/senseiwells/EssentialClient/files/8815711/latest.log)

**Comment by senseiwells** [comment]
See if [this](https://cdn.discordapp.com/attachments/967529963106492448/981589366038220841/essential-client-1.18.2-1.2.0.jar) fixes it.

**Comment by Noah765** [comment]
It didn't

[latest.log](https://github.com/senseiwells/EssentialClient/files/8816027/latest.log)

**Comment by senseiwells** [comment]
Ah. You are running 1.18.1, unfortunately I am no longer supporting that version of the mod. The mod I sent was for version 1.18.2.

**Comment by Noah765** [comment]
It worked! (Thanks for the quick responses btw.)

**Comment by Noah765** [comment]
Unfortunately I have to reopen this issue because my game crashed again after loading client scripts. Log:

[latest.log](https://github.com/senseiwells/EssentialClient/files/8837424/latest.log)

**Comment by senseiwells** [comment]
This isn't related to feather client - I made a mistake but I have fixed it, [this](https://cdn.discordapp.com/attachments/967529963106492448/982585062723825694/essential-client-1.17.1-1.2.0.jar) should fix this issue

**Comment by Noah765** [comment]
The version you sent me was for 1.17, I manually changed the version to 1.18 and got this error message

[latest.log](https://github.com/senseiwells/EssentialClient/files/8837497/latest.log)

**Comment by senseiwells** [comment]
Sorry lol, [here](https://cdn.discordapp.com/attachments/918649771844042752/982586407526760478/essential-client-1.18.2-1.2.0.jar) is the 1.18.2 version

**Comment by Noah765** [comment]
Works! Now I need to figure out how to save data in the new version
