### ISSUE TITLE
Incompatible with RebindAllTheKeys

### ISSUE THREAD

**Issue by soulsoiledit** [senseiwells/EssentialClient#50]
RebindAllTheKeys adds the functionality to rebind normally locked keybinds. When loaded with EssentialClient, the game crashes upon launch.

[crash-2022-07-06_12.59.21-client.txt](https://pastebin.com/qghLZT03)

**Comment by senseiwells** [comment]
[This version](https://cdn.discordapp.com/attachments/918649771844042752/995369792993239070/essential-client-1.19-1.2.4-BETA-090722.jar) should fix your issue

**Comment by soulsoiledit** [comment]
Looks like it still conflicts with the custom F3 debug screen keybind option.

[crash-2022-07-09_19.59.14-client.txt](https://pastebin.com/05b69tkd)

**Comment by senseiwells** [comment]
[This version](https://cdn.discordapp.com/attachments/900049355887763508/999453020037333092/essential-client-1.19-1.2.4-BETA-210722.jar) should fix all compatability issues with RebindAllTheKeys :)

**Comment by soulsoiledit** [comment]
[crash-2022-07-20_18.45.06-client.txt](https://pastebin.com/jUm1vLuX)
