### ISSUE TITLE
Conflicts with slight-gui-modifications

### ISSUE THREAD

**Issue by CodeF53** [senseiwells/EssentialClient#57]
https://modrinth.com/mod/slight-gui-modifications

Mirror Issue https://github.com/shedaniel/slight-gui-modifications/issues/76

[latest.log](https://github.com/shedaniel/slight-gui-modifications/files/9173067/latest.log)

**Comment by senseiwells** [comment]
This version should fix your issue: https://github.com/senseiwells/EssentialClient/actions/runs/2723381180

**Comment by senseiwells** [comment]
This should fix your issue: https://github.com/senseiwells/EssentialClient/actions/runs/2723907544
