### ISSUE TITLE
Player.get().attack('hold') is inconsistent

### ISSUE THREAD

**Issue by y2k04** [senseiwells/EssentialClient#83]
If I use this command and try to break a block (without using the attackBlock command) it will just make it act like the attack button is stuck. If you attack a torch, it breaks (because it has a low break tolerance), if you try breaking a block, nothing will happen. The break animation wouldn't even play. Your hand would just be stuck.

I just want to be able to hold down the attack button (as the command suggests), but it doesn't at all.

**Comment by senseiwells** [comment]
You can download the latest dev build here: https://github.com/senseiwells/EssentialClient/actions/runs/3536585242

**Comment by y2k04** [comment]
Did you mean to [attempt to] compile it for 1.18.2? Or was it meant to be 1.19.2? (This issue is present on 1.19.2, haven't tested any other versions).

**Comment by senseiwells** [comment]
It’s fixed in all versions. The compilation failed - it compiles to all versions. Try again: https://github.com/senseiwells/EssentialClient/actions/runs/3536641773

if it doesn’t work I’ll have to fix it tomorrow

**Comment by y2k04** [comment]
That fixed it, thank you!
