### ISSUE TITLE
Clientscript crash

### ISSUE THREAD

**Issue by glaav** [senseiwells/EssentialClient#84]
Clientscript crashing with "WorldeditCUI" running when chat message sent
![image](https://user-images.githubusercontent.com/112773448/201957590-5ddb7e1b-9fe4-41a8-9bd1-63e2252219cf.png)
[crash-15-11-2022_16-22-32.txt](https://github.com/senseiwells/EssentialClient/files/10013926/crash-15-11-2022_16-22-32.txt)

**Comment by senseiwells** [comment]
You can download the latest dev build here: https://github.com/senseiwells/EssentialClient/actions/runs/3536585242
