### ISSUE TITLE
Mod incompatibility >>> Cardinal Ice Boats

### ISSUE THREAD

**Issue by sternschnaube** [senseiwells/EssentialClient#86]
https://pastebin.com/raw/JxMrmtVq

The Mod: https://github.com/CodeF53/CardinalIceBoats

**Comment by senseiwells** [comment]
This should now be fixed, you can download the latest test build [here](https://github.com/senseiwells/EssentialClient/actions/runs/3772440002).

**Comment by sternschnaube** [comment]
Thank you. Everything looks fine now 😊
