### ISSUE TITLE
Suggestion: Make the client prioritise carpet rules available on the client over database

### ISSUE THREAD

**Issue by glaav** [senseiwells/EssentialClient#88]
Carpet rule allowSpawningOfflinePlayers giving out error when being edited from essential client carpet menu
![image](https://user-images.githubusercontent.com/112773448/211206973-3695f50e-b562-45b4-9f23-47cd7d327082.png)

Apparently, carpet dosen't have this option while essential client shows it.
![image](https://user-images.githubusercontent.com/112773448/211207031-962884e5-4a3c-46af-a8c2-ed2c65246a1b.png)
![image](https://user-images.githubusercontent.com/112773448/211207048-b8d4a399-64ad-4c84-9977-bb4e98de0876.png)

Isn't it possible to get the possible values from carpet instead of it being hard coded? (in case it is)

**Comment by glaav** [comment]
wait but i have the latest carpet version for 1.19.3

**Comment by senseiwells** [comment]
Oops, that's my mistake, this was actually an issue with the database ([see here](https://github.com/Crec0/carpet-rules-database/pull/10)). This has now been fixed, so when the database next updates this should be fixed.

However I will leave this issue open as what I previously stated is still valid.
