### ISSUE TITLE
chest.onClick(fun(item,slot,action){}) Expect to add "action" distinguish (left click) and (right click)

### ISSUE THREAD

**Issue by JiangZeOvO** [senseiwells/EssentialClient#95]

**Comment by senseiwells** [comment]
I don't understand the issue?
Can you please elaborate.

**Comment by JiangZeOvO** [comment]
![image](https://user-images.githubusercontent.com/101352564/215345221-afbbcf24-c831-4345-8436-9df7a5f48a08.png)
this action Is there a way to distinguish left  click and right click

**Comment by JiangZeOvO** [comment]
at present left click and right click action == PICKUP

**Comment by senseiwells** [comment]
You can download the latest dev build here: https://github.com/senseiwells/EssentialClient/actions/runs/4038031820
