### ISSUE TITLE
Entity.of(entityId) error

### ISSUE THREAD

**Issue by JiangZeOvO** [senseiwells/EssentialClient#96]
![image](https://user-images.githubusercontent.com/101352564/215352660-92431540-be86-4066-9c20-3526fbd747b2.png)
![image](https://user-images.githubusercontent.com/101352564/215352705-6e060a8a-3b16-44e4-a089-3c24304ebbe3.png)

**Comment by JiangZeOvO** [comment]
Entity.of('minecraft:cow');

**Comment by senseiwells** [comment]
You can download the latest dev build here: https://github.com/senseiwells/EssentialClient/actions/runs/4038443903
