### ISSUE TITLE
Network.openUrl Error

### ISSUE THREAD

**Issue by JiangZeOvO** [senseiwells/EssentialClient#99]
![image](https://user-images.githubusercontent.com/101352564/218940465-f2fee860-b975-42b9-ae3b-a3a4a8fd26f1.png)

**Comment by senseiwells** [comment]
Your system doesn't support opening URLS.
What OS are you using?

**Comment by JiangZeOvO** [comment]
windows 11 , It can be opened some time ago

**Comment by senseiwells** [comment]
Unfortunately I cannot reproduce this issue.
If you are still facing this issue you are welcome to reopen this issue
but please provide the version of Java you are using, the version of your mod, and the script you are using.
